### ISSUE TITLE
It is not clear which model to get from the compvis

### ISSUE THREAD

**Issue by ABBEN4** [altryne/sd-webui-colab#1]
Hello,

Thank you for the colab, really cool idea ! Having issue with connecting to the model.

The link provided to download the model links to the one with diffuser and no packaged model. Should we use this link ? https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/tree/main

Also, if so should we get sd-v1-4-full-ema.ckpt or sd-v1-4.ckpt and keep them named as they are ?

Else, should we get all the files and folders from here : https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main

I would recommend starting the colab with a detailed explanation on this part. If you can clarify this for me, I can update the colab with that and send it back to you to push here :)

Thank you,

Abdé

**Comment by altryne** [comment]
Just this file: 
`sd-v1-4.ckpt`

**Comment by ABBEN4** [comment]
> Just this file: `sd-v1-4.ckpt`

Great, thank you,

I would suggest replacing the link provided in the colab by this one then : https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/tree/main

and indicating the model to get !

Maybe something like this right before step 1 ? 

------

##0. Premiminary steps

1.   Register on [HugginFace](https://huggingface.co)
2.  Go to [To the model page ](https://huggingface.co/CompVis/stable-diffusion-v1-4) and accept the conditions
3.  Go to [model folder](https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/tree/main) and download the sd-v1-4.ckpt file 
4.   Upload this file into your google Drive (precise the folder here) - this might take a while, grab a coffee
