### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by slumberspirit** [altryne/sd-webui-colab#19]
### What happened?

I run into this error and the images saved to drive are just black: Exception: No usable font found (tried arial.ttf, DejaVuSans.ttf)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Colab

### Relevant log output

```shell
File "scripts/webui.py", line 419, in image_grid
    fnt = get_font(30)
  File "scripts/webui.py", line 401, in get_font
    raise Exception(f"No usable font found (tried {', '.join(fonts)})")
Exception: No usable font found (tried arial.ttf, DejaVuSans.ttf)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by semlar** [comment]
I also ran into this earlier; as a temporary workaround you can get around it by checking the "add LDSR" option in the upscaler section which the font is currently incorrectly nested under.

**Comment by slumberspirit** [comment]
Thanks! Clicking add LDSR worked.

**Comment by altryne** [comment]
This was my bad, @semlar thanks for this suggested fix. 
@slumberspirit you shouldn't have to download a full 2GB thing now to fix a fucking free font, I apologize (but download it anyway as it allows you to upscale in the imageLAb!) 

This was fixed
