### ISSUE TITLE
Failed inference for GFPGAN

### ISSUE THREAD

**Issue by eungangku** [altryne/sd-webui-colab#2]
Failed inference for GFPGAN: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward).

I'm having this message when I try to process the image with GFPGAN in the GFPGAN tab of the UI.

**Comment by altryne** [comment]
Hey, thanks for this, do you mind trying to check this feature on: 
![CleanShot 2022-08-29 at 12 41 24@2x](https://user-images.githubusercontent.com/463317/187274425-5b844525-8200-4c86-9c15-a7a7062ded27.jpg)
and see if it solves it?

**Comment by eungangku** [comment]
> Hey, thanks for this, do you mind trying to check this feature on: 
> ![CleanShot 2022-08-29 at 12 41 24@2x](https://user-images.githubusercontent.com/463317/187274425-5b844525-8200-4c86-9c15-a7a7062ded27.jpg)
> and see if it solves it? 

I checked that the both features are turned on. Unfortunately the error isn't gone :(

**Comment by altryne** [comment]
I meant toggle them off and see?

**Comment by altryne** [comment]
Closing for now
