### ISSUE TITLE
Stuck when using batch size larger than 1

### ISSUE THREAD

**Issue by filiphorvat** [altryne/sd-webui-colab#3]
When the batch size is set to 2 or more, the web UI doesn't show the created images, continues "loading" them forever and doesn't react to inputting either new prompts or the same one.
The images still appear in the google drive folder after they're generated.

**Comment by filiphorvat** [comment]
Never mind, batch count with batch size set to 1 was what I was looking for.

**Comment by altryne** [comment]
@filiphorvat thanks for the issue, can you open a discussion about this confusiong point in https://github.com/hlky/stable-diffusion-webui discussions? Would be helpful to know what confuses folks and how to fix

**Comment by Puncia** [comment]
I have the same issue. I don't see a discussion open there and I think it's only related to colab since I don't have that problem on my local machine; should open a discussion regardless?

**Comment by altryne** [comment]
missed this, @Puncia the batch_size and batch_num were reimplemented on the main branch, and I'm waiting for a stable release to pin point to
