### ISSUE TITLE
[suggestion] add download checkpoint instruction to the colab.

### ISSUE THREAD

**Issue by MiladInk** [altryne/sd-webui-colab#7]
Thank you very much for the great colab. I am opening this issue because I went to the colab from twitter and could not figure out why the code is not running until I found this repository and understood the step of downloading the checkpoints is missing from the colab itself. Would you mind adding it to the colab?

tldr; add "download stable diffusion checkpoint and put it in AI folder" in the colab :) 

Thanks.

**Comment by MiladInk** [comment]
Hi altryne, it is not a duplicate of 4. I am just saying that please add instructions to do so on the colab also. I am not asking fo r putting the downloaded version of the ckpt there.

**Comment by altryne** [comment]
You mean maybe that this part is not clear? 
![CleanShot 2022-08-30 at 16 53 54@2x](https://user-images.githubusercontent.com/463317/187557525-98488bb0-19eb-4f13-99e7-66c496ffe206.jpg)

**Comment by MiladInk** [comment]
Oh, I've never seen that because the cells are in collapsed mode by defauklt (as shown in the attached image.) and they run just fine without any error.

 I guess it would be much better to just raise an error of the checkpoint file does not exist and prompt that they download it from huggingface.
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/18356953/187557870-116f2bee-f6ad-41fe-8466-e0a07af09515.png">
